### ISSUE TITLE
Incorrect byte order of resolve's port value

### ISSUE THREAD

**Issue by ggodet-bar** [stbuehler/rust-async-dnssd#1]
The port returned by calls to service::resolve has an inconsistent endianness (at least on macOS). My current workaround is to use `byteorder` to rearrange the value (the tokyo-core code below could certainly be more efficient):

~~~~rust
match core.run(browse_result.resolve(&handle).unwrap().into_future()) {
  Ok( (resolve_result, _) ) => {
    let resolve_details = resolve_result.unwrap() ;
    let mut port_buf = [0;4] ;
    byteorder::NetworkEndian::write_u16(&mut port_buf, resolve_details.port) ;
    let actual_port = byteorder::NativeEndian::read_u16(&port_buf) ;
    // etc.
  },
  // etc.
}
~~~~

**Comment by stbuehler** [comment]
I'll look into it.

Also: [`to_be`](https://doc.rust-lang.org/std/primitive.u16.html#method.from_be) is probably an easier way to byteswap on little endian :) (and `port_buf` only needs two bytes, not four)

**Comment by ggodet-bar** [comment]
Thanks! I hadn't noticed `to_be`, and thanks for spotting my size mistake :)
