### ISSUE TITLE
build fails when building with cross for aarch64

### ISSUE THREAD

**Issue by tspoppdepr** [stbuehler/rust-async-dnssd#15]
Hi,

I'm trying to build the rust-async-dnssd project with cross for aarch64 using "cross build --target aarch64-unknown-linux-gnu".  Unfortunately, it's failing with the following error within async-dnssd-0.4.0:

```
error[E0308]: mismatched types
  --> /cargo/registry/src/github.com-1ecc6299db9ec823/async-dnssd-0.4.0/src/service/mod.rs:75:5
   |
75 |                 buf.as_mut_ptr() as *mut i8,
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u8`, found `i8`
   |
   = note: expected raw pointer `*mut u8`
              found raw pointer `*mut i8`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: could not compile `async-dnssd`.
```

It seems this error does not appear when building with cargo.

**Comment by stbuehler** [comment]
Thanks for reporting, should be fixed now on master, also published a 0.4.1 including the fix.

Hint: please use the "Insert Code" helper (or the corresponding markdown syntax) instead of "quoting" command-line output, so the result is actually readable :)
