### ISSUE TITLE
DNSServiceRegister gives not supported on Linux

### ISSUE THREAD

**Issue by Miezhiko** [stbuehler/rust-async-dnssd#16]
Hello, is it expected?

calling `register_extended` returns `not supported` error.
is it possible to make it working with avahi?

(even with warning about partially missing functionality)

**Comment by stbuehler** [comment]
Hi,

sorry it took me so long to respond.

`register_extended` works for me (debian bullseye/sid with avahi); `register` uses `register_extended` itself too.

Maybe you're trying to use options in `RegisterData` that aren't supported by avahi? Can you post example code that isn't working?

**Comment by Miezhiko** [comment]
@stbuehler those are using currently (sorry for long respond too)

```rust
RegisterData {
  flags: async_dnssd::RegisterFlags::NO_AUTO_RENAME | async_dnssd::RegisterFlags::UNIQUE,
  name: Some(&name),
  ..Default::default()
}
```

**Comment by stbuehler** [comment]
Well, it looks like avahi simply doesn't support (those?) flags. Not quite sure what you mean with "make it working with avahi" - but I don't see a sane way fixing it in this crate - this crate is about the `dnssd` API, not the `avahi` one.

If `avahi-dnssd` can't handle these flags I doubt I could do a better job by wrapping the avahi API myself.

Sorry, but I don't think I can help you.

**Comment by Miezhiko** [comment]
@stbuehler I was trying without flags but got "unknown error"

**Comment by stbuehler** [comment]
I tried this (modified `register.rs` in current git head), and it seems to work fine:

```rust
#[tokio::main(flavor = "current_thread")]
async fn main() -> std::io::Result<()> {
	// Use `cargo run --example register`

	let rd = async_dnssd::RegisterData {
		name: Some("foobar"),
		..Default::default()
	};

	let (_registration, result) = async_dnssd::register_extended("_ssh._tcp", 2022, rd)?.await?;
	println!("Registered: {:?}", result);

	// wait until killed
	futures::future::pending::<()>().await;
	Ok(())
}
```

This "unknown error" - does it come with the avahi warning or without?

**Comment by Miezhiko** [comment]
@stbuehler yes actually, with ```The program 'x' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!```

**Comment by stbuehler** [comment]
Then my only guess is that avahi-dnssd added support for the name option in a later version; still nothing I can do about that.

Perhaps you'd actually need a `avahi-async` crate (which doesn't exist so far) - but certainly does sound like something useful. Perhaps I'll give it a try, but not as part of this crate.
